### ISSUE TITLE
RedCloth escapes images when the alt text includes a space

### ISSUE THREAD

**Issue by samstickland** [jgarber/redcloth#26]
Hi,

I've encountered a very weird bug whilst trying to upgrade an old application. I've verified this problem with Ruby 2.3.0 and RedCloth 4.3.1

Without a space in the alt text:

```
> str = '<img src="http://assets/image_460.jpeg" alt=”Some"/>'
> RedCloth.new(str).to_html
 => "<p><img src=\"http://assets/image_460.jpeg\" alt=”Some\"/></p>"
```

With a space in the alt text:

```
> str = '<img src="http://assets/image_460.jpeg" alt=”Some text"/>'
> RedCloth.new(str).to_html
 => "<p>&lt;img src=&#8220;http://assets/image_460.jpeg&#8221; alt=”Some text&quot;/&gt;</p>"
```

Any ideas on where to start hunting? I'm happy to roll up my sleeves and dig in, this problem is preventing us from upgrading an old, but very important application, to Ruby 1.9.3.

**Comment by joshuasiler** [comment]
Hi. The problem appears to be you are using the ” char instead of ". 

    str = '<img src="http://assets/image_460.jpeg" alt="Some text"/>'

rather than: 

    str = '<img src="http://assets/image_460.jpeg" alt=”Some text"/>'

will work correctly.

**Comment by samstickland** [comment]
Thanks!

That's weird.  This means something in our application has started returning  ” char instead of " since we upgraded to Ruby 1.9.3!

Well at least I know where to look now! :)

**Comment by samstickland** [comment]
Ah, apologies. The ” quote was something that must had gotten accidentally introduced. The true problem is with data attributes:

This works:
```
>> str = "<img src=\"http://example.com/image.jpg\" />"
>> o = RedCloth.new(str).to_html
=> "<p><img src=\"http://example.com/image.jpg\" /></p>"
```

This doesn't:

```
>> str = "<img src=\"http://example.com/image.jpg\" data-fluid=true />"
>> o = RedCloth.new(str).to_html
=> "<p>&lt;img src=&#8220;http://example.com/image.jpg&#8221; data-fluid=true /&gt;</p>"
```

**Comment by samstickland** [comment]
Interestingly closing the img tag in the old style way works:

```
>> str = "<img src=\"http://example.com/image.jpg\" data-fluid=true></img>"
>> o = RedCloth.new(str).to_html
=> "<p><img src=\"http://example.com/image.jpg\" data-fluid=true></img></p>"
```

Unfortunately we aren't free to adopt that approach, since raw HTML in our CMS can come from a number of staff and volunteers. It might provide a clue though?

**Comment by samstickland** [comment]
OK, the conditions that cause this are:

- Shorttag img
AND
- Unquoted attributes

Putting `data-fluid="true"` works OK.

I'm going to investigate trying to do some preprocessing on our HTML to quote the attributes.. Trying to figure out how Ragel does it's parsing is probably beyond me for now.

**Comment by joshuasiler** [comment]
This makes sense, I think the quotes are required for the tag to be correct.

**Comment by samstickland** [comment]
Technically the quotes are optional for HTML5. But in this case I was able
to alter our HTML generators to return quoted data attributes.

2016-05-25 16:35 GMT+01:00 Joshua Siler <notifications@github.com>:

**Comment by joshuasiler** [comment]
good to know thanks
