### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by brodock** [jgarber/redcloth#31]
I would like to ask if JRuby support is out forever or it will make a comeback in a future release, as the statement in the [README](https://github.com/jgarber/redcloth#attention---deprecating-jruby-and-windows-support-in-version-43) is a little ambiguous about the support in the roadmap.

**Comment by joshuasiler** [comment]
Currently I have no plans to work on JRuby support. I would be happy to facilitate the work if another contributor would like to get it done.

**Comment by headius** [comment]
We need to have RedCloth on JRuby and had not realized it had been dropped. What can we do to help?
