### ISSUE TITLE
Ruby 2.1.9 installs extension poorly.

### ISSUE THREAD

**Issue by DouglasAllen** [jgarber/redcloth#36]
I ran a simple example from https://github.com/DouglasAllen/code-Metaprogramming_Ruby/blob/master/raw-code/Part_I_Metaprogramming_Ruby/ch01_Monday_The_Object_Model/the-ruby-object-model-and-metaprogramming/v-dtrubyom-v-02-code/textile.rb

The Kernel was looking for it in several lib directories.
    The $LOAD_PATH was:
    C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/RedCloth-4.3.2/lib
    C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/RedCloth-4.3.2/lib/case_sensitive_require
    C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/RedCloth-4.3.2/ext
    C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/RedCloth-4.3.2
    C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0
    C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/x64-msvcrt
    C:/Ruby21-x64/lib/ruby/site_ruby
    C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0
    C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0/x64-msvcrt
    C:/Ruby21-x64/lib/ruby/vendor_ruby
    C:/Ruby21-x64/lib/ruby/2.1.0
    C:/Ruby21-x64/lib/ruby/2.1.0/x64-mingw32

But it wasn't in any of them. 
I got it to work by putting the redcloth_scan.so in C:\Ruby21-x64\lib\ruby\site_ruby\2.1.0\2.1\redcloth_scan.so
as that was one were the Kernel expected it.

What version of Ruby was your last build target?

**Comment by joshuasiler** [comment]
Hi,
Unfortunately we are no longer able to maintain the windows builds as part of this repository, just because we don't have any active contributors running on the Windows platform.  If you're able to get it fixed up, please submit a PR and we'd be happy to include any improvements to the process.
Josh

**Comment by DouglasAllen** [comment]
Will it still work in other platforms with that simple change in my first post? Non issue for you eh?
No windows users out there in dev land? Same old story. Where do I learn it then? I can't afford s MacBook.
I'll request a pull but heck if I know what I'm doing.

**Comment by joshuasiler** [comment]
Douglas - one option would be to run Linux under VirtualBox on your Windows machine. That's how my development is done. 

Good luck!

**Comment by DouglasAllen** [comment]
Yes I understand that but I'm lazy and it was just a quick test to see if RedCloth was doing it's job here on Windows 10. It seems like a simple thing if we can get on the same page with the library directory structure.
Here's my run of 
>> RbConfig::CONFIG.sort.each { |keys| p keys }
["ALLOCA", ""]
["AR", "ar"]
["ARCHFILE", ""]
["ARCH_FLAG", ""]
["AS", "as"]
["ASFLAGS", ""]
["BTESTRUBY", "$(MINIRUBY)"]
["BUILTIN_TRANSSRCS", " newline.c"]
["CAPITARGET", "nodoc"]
["CC", "x86_64-w64-mingw32-gcc"]
["CCDLFLAGS", ""]
["CC_VERSION", "x86_64-w64-mingw32-gcc -v"]
["CFLAGS", " -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration"]
["CHDIR", "cd"]
["COMMON_HEADERS", "winsock2.h windows.h"]
["COMMON_LIBS", "m"]
["COMMON_MACROS", ""]
["COUTFLAG", "-o "]
["CP", "cp"]
["CPP", "x86_64-w64-mingw32-gcc -E"]
["CPPFLAGS", "-DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64 "]
["CPPOUTFILE", "-o conftest.i"]
["CROSS_COMPILING", "no"]
["CXX", "x86_64-w64-mingw32-g++"]
["CXXFLAGS", " -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration"]
["DEFS", "-D_FILE_OFFSET_BITS=64"]
["DESTDIR", "C:"]
["DLDFLAGS", " -Wl,--enable-auto-image-base,--enable-auto-import $(DEFFILE)"]
["DLDLIBS", ""]
["DLEXT", "so"]
["DLEXT2", ""]
["DLLWRAP", "dllwrap"]
["DLNOBJ", "dln.o"]
["DOT", ""]
["DOXYGEN", ""]
["DTRACE", ""]
["DTRACE_EXT", "dmyh"]
["DTRACE_GLOMMED_OBJ", ""]
["DTRACE_OBJ", ""]
["ECHO_C", ""]
["ECHO_N", "-n"]
["ECHO_T", ""]
["EGREP", "/usr/bin/grep -E"]
["ENABLE_SHARED", "yes"]
["EXECUTABLE_EXTS", ".exe .com .cmd .bat"]
["EXEEXT", ".exe"]
["EXPORT_PREFIX", " "]
["EXTDLDFLAGS", ""]
["EXTLDFLAGS", ""]
["EXTOUT", ".ext"]
["EXTSTATIC", ""]
["GCC", "yes"]
["GNU_LD", "yes"]
["GREP", "/usr/bin/grep"]
["INSTALL", "/usr/bin/install -c"]
["INSTALLDOC", "nodoc"]
["INSTALL_DATA", "/usr/bin/install -c -m 644"]
["INSTALL_PROGRAM", "/usr/bin/install -c"]
["INSTALL_SCRIPT", "/usr/bin/install -c"]
["LD", "ld"]
["LDFLAGS", "-L. "]
["LDSHARED", "x86_64-w64-mingw32-gcc -shared $(if $(filter-out -g -g0,-g),,-s)"]
["LDSHAREDXX", "x86_64-w64-mingw32-g++ -shared $(if $(filter-out -g -g0,-g),,-s)"]
["LIBEXT", "a"]
["LIBPATHENV", ""]
["LIBPATHFLAG", " -L%s"]
["LIBRUBY", "libx64-msvcrt-ruby210.dll.a"]
["LIBRUBYARG", "-lx64-msvcrt-ruby210"]
["LIBRUBYARG_SHARED", "-lx64-msvcrt-ruby210"]
["LIBRUBYARG_STATIC", "-lx64-msvcrt-ruby210-static"]
["LIBRUBY_A", "libx64-msvcrt-ruby210-static.a"]
["LIBRUBY_ALIASES", ""]
["LIBRUBY_RELATIVE", "yes"]
["LIBRUBY_SO", "x64-msvcrt-ruby210.dll"]
["LIBS", "-lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi "]
["LINK_SO", ""]
["LN_S", "cp -pR"]
["MAINLIBS", ""]
["MAJOR", "2"]
["MAKEDIRS", "/usr/bin/mkdir -p"]
["MAKEFILES", "Makefile GNUmakefile"]
["MANTYPE", "man"]
["MINOR", "1"]
["MKDIR_P", "/usr/bin/mkdir -p"]
["NACL_SDK_ROOT", ""]
["NACL_SDK_VARIANT", ""]
["NACL_TOOLCHAIN", ""]
["NM", "nm"]
["NROFF", "/bin/false"]
["NULLCMD", ":"]
["OBJCOPY", ":"]
["OBJDUMP", "objdump"]
["OBJEXT", "o"]
["OUTFLAG", "-o "]
["PACKAGE", "ruby"]
["PACKAGE_BUGREPORT", ""]
["PACKAGE_NAME", ""]
["PACKAGE_STRING", ""]
["PACKAGE_TARNAME", ""]
["PACKAGE_URL", ""]
["PACKAGE_VERSION", ""]
["PATCHLEVEL", "490"]
["PATH_SEPARATOR", ":"]
["PKG_CONFIG", ""]
["PLATFORM_DIR", "win32"]
["POSTLINK", ":"]
["PREP", "miniruby.exe"]
["PYTHON", "C:\\\\Python\\\\Python27"]
["RANLIB", "ranlib"]
["RDOCTARGET", "nodoc"]
["RI_BASE_NAME", "ri"]
["RM", "rm -f"]
["RMALL", "rm -fr"]
["RMDIR", "rmdir --ignore-fail-on-non-empty"]
["RMDIRS", "rmdir --ignore-fail-on-non-empty -p"]
["RPATHFLAG", ""]
["RUBYW_BASE_NAME", "rubyw"]
["RUBYW_INSTALL_NAME", "rubyw"]
["RUBY_BASE_NAME", "ruby"]
["RUBY_EXEC_PREFIX", ""]
["RUBY_INSTALL_NAME", "ruby"]
["RUBY_LIB_VERSION", ""]
["RUBY_LIB_VERSION_STYLE", "3\t/* full */"]
["RUBY_PROGRAM_VERSION", "2.1.9"]
["RUBY_RELEASE_DATE", "2016-03-30"]
["RUBY_SEARCH_PATH", ""]
["RUBY_SO_NAME", "x64-msvcrt-ruby210"]
["RUBY_VERSION_NAME", "ruby-2.1.0"]
["RUNRUBY_COMMAND", "$(MINIRUBY) $(srcdir)/tool/runruby.rb --extout=.ext $(RUNRUBYOPT)"]
["SET_MAKE", ""]
["SHELL", "/bin/sh"]
["SOLIBS", "-lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi "]
["STATIC", ""]
["STRIP", "strip"]
["SYMBOL_PREFIX", ""]
["TEENY", "0"]
["TEST_RUNNABLE", "yes"]
["THREAD_MODEL", "win32"]
["TRY_LINK", ""]
["UNIVERSAL_ARCHNAMES", ""]
["UNIVERSAL_INTS", ""]
["USE_RUBYGEMS", "YES"]
["WERRORFLAG", "-Werror"]
["WINDRES", "windres"]
["arch", "x64-mingw32"]
["archdir", "C:/Ruby21-x64/lib/ruby/2.1.0/x64-mingw32"]
["archincludedir", "C:/Ruby21-x64/include/x64-mingw32"]
["archlibdir", "C:/Ruby21-x64/lib/x64-mingw32"]
["bindir", "C:/Ruby21-x64/bin"]
["build", "i686-pc-mingw32"]
["build_alias", ""]
["build_cpu", "i686"]
["build_os", "mingw32"]
["build_vendor", "pc"]
["cflags", " -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration"]
["codesign", ""]
["configure_args", " '--enable-shared' '--disable-install-doc' 'debugflags=-g' 'CPPFLAGS=-DFD_SETSIZE=2048' '--host=x86_64-w64-mingw32' '--prefix=' 'host_alias=x86_64-w64-mingw32' 'LDFLAGS='"]
["cppflags", ""]
["cxxflags", " -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration"]
["datadir", "C:/Ruby21-x64/share"]
["datarootdir", "C:/Ruby21-x64/share"]
["debugflags", "-g"]
["docdir", "C:/Ruby21-x64/share/doc/ruby"]
["dvidir", "C:/Ruby21-x64/share/doc/ruby"]
["exec", "exec"]
["exec_prefix", "C:/Ruby21-x64"]
["host", "x86_64-w64-mingw32"]
["host_alias", "x86_64-w64-mingw32"]
["host_cpu", "x86_64"]
["host_os", "mingw32"]
["host_vendor", "w64"]
["htmldir", "C:/Ruby21-x64/share/doc/ruby"]
["includedir", "C:/Ruby21-x64/include"]
["infodir", "C:/Ruby21-x64/share/info"]
["libdir", "C:/Ruby21-x64/lib"]
["libdirname", "libdir"]
["libexecdir", "C:/Ruby21-x64/libexec"]
["localedir", "C:/Ruby21-x64/share/locale"]
["localstatedir", "C:/Ruby21-x64/var"]
["mandir", "C:/Ruby21-x64/share/man"]
["oldincludedir", "/usr/include"]
["optflags", "-O3 -fno-omit-frame-pointer -fno-fast-math"]
["pdfdir", "C:/Ruby21-x64/share/doc/ruby"]
["prefix", "C:/Ruby21-x64"]
["psdir", "C:/Ruby21-x64/share/doc/ruby"]
["ridir", "C:/Ruby21-x64/share/ri"]
["ruby_install_name", "ruby"]
["ruby_pc", "ruby-2.1.pc"]
["ruby_version", "2.1.0"]
["rubyarchdir", "C:/Ruby21-x64/lib/ruby/2.1.0/x64-mingw32"]
["rubyarchhdrdir", "C:/Ruby21-x64/include/ruby-2.1.0/x64-mingw32"]
["rubyarchprefix", "C:/Ruby21-x64/lib/ruby/x64-mingw32"]
["rubyhdrdir", "C:/Ruby21-x64/include/ruby-2.1.0"]
["rubylibdir", "C:/Ruby21-x64/lib/ruby/2.1.0"]
["rubylibprefix", "C:/Ruby21-x64/lib/ruby"]
["rubysitearchprefix", "C:/Ruby21-x64/lib/ruby/x64-msvcrt"]
["rubyw_install_name", "rubyw"]
["sbindir", "C:/Ruby21-x64/sbin"]
["setup", "Setup"]
["sharedstatedir", "C:/Ruby21-x64/com"]
["sitearch", "x64-msvcrt"]
["sitearchdir", "C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/x64-msvcrt"]
["sitearchhdrdir", "C:/Ruby21-x64/include/ruby-2.1.0/site_ruby/x64-msvcrt"]
["sitearchincludedir", "C:/Ruby21-x64/include/x64-msvcrt"]
["sitearchlibdir", "C:/Ruby21-x64/lib/x64-msvcrt"]
["sitedir", "C:/Ruby21-x64/lib/ruby/site_ruby"]
["sitehdrdir", "C:/Ruby21-x64/include/ruby-2.1.0/site_ruby"]
["sitelibdir", "C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0"]
["strict_warnflags", ""]
["sysconfdir", "C:/Ruby21-x64/etc"]
["target", "x86_64-w64-mingw32"]
["target_alias", ""]
["target_cpu", "x64"]
["target_os", "mingw32"]
["target_vendor", "w64"]
["topdir", "C:/Ruby21-x64/lib/ruby/2.1.0/x64-mingw32"]
["try_header", ""]
["vendorarchdir", "C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0/x64-msvcrt"]
["vendorarchhdrdir", "C:/Ruby21-x64/include/ruby-2.1.0/vendor_ruby/x64-msvcrt"]
["vendordir", "C:/Ruby21-x64/lib/ruby/vendor_ruby"]
["vendorhdrdir", "C:/Ruby21-x64/include/ruby-2.1.0/vendor_ruby"]
["vendorlibdir", "C:/Ruby21-x64/lib/ruby/vendor_ruby/2.1.0"]
["warnflags", "-Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration"]

**Comment by DouglasAllen** [comment]
Can you try this?
 It works for me.
line 12 redcloth.rb
prefix = conf['arch'] =~ /mswin|mingw/ ? '' : "#{conf['MAJOR']}.#{conf['MINOR']}.#{conf['TEENY']}/"

**Comment by DouglasAllen** [comment]
MinGW doesn't like the version style. Perhaps it will still work in others builds. Should I go ahead and put that in a branch and if so which one?

**Comment by DouglasAllen** [comment]
Even if I built it in a unix/linux dev env that wouldn't fix the problem would it? I appreciate that you even considered us mswin/mingw users though. For now my problem is solved with this little change.

**Comment by MSP-Greg** [comment]
@DouglasAllen 

I believe you can leave `redcloth_scan.so` in its original location (which is where updates should place it)

`C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/RedCloth-4.3.2`

and apply the patch you mentioned.  Or, the first code lines I use:

```ruby
Object.send(:remove_const, :RedCloth) if Object.const_defined?(:RedCloth) && RedCloth.is_a?(Class)

begin
  require "redcloth_scan"
rescue LoadError => e
  e.message << %{\nCouldn't load redcloth_scan\nThe $LOAD_PATH was:\n#{$LOAD_PATH.join("\n")}}
  raise e
end
```
I'll do some more testing and submit a patch.  FYI, I'm building with code based on [RubyInstaller2](https://github.com/oneclick/rubyinstaller2) using

`ruby 2.5.0dev (2017-05-18 trunk 58780) [x64-mingw32]`

and installed with

`gem install RedCloth --platform-ruby`.

Just used it to create several html files from *.textile files also...

@joshuasiler does RedCloth allow code blocks surrounded by backticks?  I think GitHub's wiki pages parse that way.  See [EventMachine wiki](https://github.com/eventmachine/eventmachine/wiki/Code-Snippets).  If you click edit or clone it, you'll see that it's textile, or at least 'edit mode' shows 'Textile'...
