### ISSUE TITLE
Ruby 3 in CI?

### ISSUE THREAD

**Issue by digitalmoksha** [jgarber/redcloth#71]
@joshuasiler what do you think about explicitly adding Ruby 3 into the Ci matrix?  I know `ruby-head` is in there - not sure when the last pipeline was run, so I don't know if Ruby 3 was ever tested.

I tried it myself locally.  Installing the gem under Ruby 3 seemed to work fine.  I then re-compiled it from scratch and ran the specs, which worked.  I did have to update the `rake` and `rspec` development dependencies to get it to compile.

I'm happy to put together a PR if you would consider it.

I'm curious as to whether travis is still working, or would we have to convert to GitHub actions.

**Comment by heliocola** [comment]
Thank you @MSP-Greg .
@digitalmoksha : if you want to take a stab and look at #83, please let us know.
