### ISSUE TITLE
Gem homepage on gemspec

### ISSUE THREAD

**Issue by heliocola** [jgarber/redcloth#79]
### Issue
redcloth.org is displaying a sample page with a link "Buy this domain".

### Expected
Possibility 1: display the intended https://github.com/jgarber/try-redcloth repo.
Possibility 2: change it to be either Rubygems, or GitHub repo, or GitLab repo

**Comment by heliocola** [comment]
@jgarber , @joshuasiler : do you know what is the issue/history with the domain redcloth.org?
Is it just a missing place to have the try-redcloth repo hosted?

**Comment by heliocola** [comment]
Hi there @jgarber , happy new year.
Let me know if I can get a little bit of your time get this more organized.

In the GH main page, in the About section (top right corder) there is also a link to redcloth.org that I can't change.
I want to either get the domain back, or replace with something else.

**Comment by jgarber** [comment]
Hi @heliocola! Thanks for your persistence! I'm just getting back from holiday.

Looks like I neglected to renew redcloth.org some time ago. Probably best to just remove all links to redcloth.org. #84
